export enum ActionTypes {
    FETCH_DATA = 'FETCH_DATA',
    SEND_DATA = 'SEND_DATA',
    FETCH_LOADING = 'FETCH_LOADING',
    SEND_LOADING = 'SEND_LOADING',
    FETCH_DATA_FAIL = 'FETCH_DATA_FAIL',
    SEND_DATA_FAIL = 'SEND_DATA_FAIL'
  }
  